version: '3'
services:
  julia:
    image: cerastesjl
    container_name: cerastesjl-julia
    volumes:
      - ./:/workspace/Cerastes.jl
    working_dir: /workspace/Cerastes.jl
    command: julia --project=/workspace/Cerastes.jl

  shell:
    image: cerastesjl
    container_name: cerastesjl-julia
    volumes:
      - ./:/workspace/Cerastes.jl
    working_dir: /workspace/Cerastes.jl
    command: /bin/bash

  web:
    image: cerastesjl
    container_name: cerastesjl-packagedocs
    volumes:
      - ./:/workspace/Cerastes.jl
    working_dir: /workspace/Cerastes.jl
    ports:
      - "8000:8000"
    command: make web
